/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiJobsRunRouteImport } from './routes/api/jobs/run'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiProjectsIdIndexRouteImport } from './routes/api/projects/$id/index'
import { Route as ApiProjectsIdVerifyRouteImport } from './routes/api/projects/$id/verify'
import { Route as ApiProjectsIdImportRouteImport } from './routes/api/projects/$id/import'
import { Route as ApiProjectsIdFilesRouteImport } from './routes/api/projects/$id/files'
import { Route as ApiProjectsIdAnalyzeRouteImport } from './routes/api/projects/$id/analyze'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRunRoute = ApiJobsRunRouteImport.update({
  id: '/api/jobs/run',
  path: '/api/jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/api/files/$fileId',
  path: '/api/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdIndexRoute = ApiProjectsIdIndexRouteImport.update({
  id: '/api/projects/$id/',
  path: '/api/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdVerifyRoute = ApiProjectsIdVerifyRouteImport.update({
  id: '/api/projects/$id/verify',
  path: '/api/projects/$id/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdImportRoute = ApiProjectsIdImportRouteImport.update({
  id: '/api/projects/$id/import',
  path: '/api/projects/$id/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdFilesRoute = ApiProjectsIdFilesRouteImport.update({
  id: '/api/projects/$id/files',
  path: '/api/projects/$id/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdAnalyzeRoute = ApiProjectsIdAnalyzeRouteImport.update({
  id: '/api/projects/$id/analyze',
  path: '/api/projects/$id/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/files': typeof ApiProjectsIdFilesRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/projects/$id/': typeof ApiProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/files': typeof ApiProjectsIdFilesRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/projects/$id': typeof ApiProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/files': typeof ApiProjectsIdFilesRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/projects/$id/': typeof ApiProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/projects/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/files/$fileId'
    | '/api/jobs/run'
    | '/api/jobs/'
    | '/api/projects/'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/files'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/projects/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/files/$fileId'
    | '/api/jobs/run'
    | '/api/jobs'
    | '/api/projects'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/files'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/projects/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/files/$fileId'
    | '/api/jobs/run'
    | '/api/jobs/'
    | '/api/projects/'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/files'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
  ApiJobsRunRoute: typeof ApiJobsRunRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiProjectsIdAnalyzeRoute: typeof ApiProjectsIdAnalyzeRoute
  ApiProjectsIdFilesRoute: typeof ApiProjectsIdFilesRoute
  ApiProjectsIdImportRoute: typeof ApiProjectsIdImportRoute
  ApiProjectsIdVerifyRoute: typeof ApiProjectsIdVerifyRoute
  ApiProjectsIdIndexRoute: typeof ApiProjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/run': {
      id: '/api/jobs/run'
      path: '/api/jobs/run'
      fullPath: '/api/jobs/run'
      preLoaderRoute: typeof ApiJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/': {
      id: '/api/projects/$id/'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id/'
      preLoaderRoute: typeof ApiProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/verify': {
      id: '/api/projects/$id/verify'
      path: '/api/projects/$id/verify'
      fullPath: '/api/projects/$id/verify'
      preLoaderRoute: typeof ApiProjectsIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/import': {
      id: '/api/projects/$id/import'
      path: '/api/projects/$id/import'
      fullPath: '/api/projects/$id/import'
      preLoaderRoute: typeof ApiProjectsIdImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/files': {
      id: '/api/projects/$id/files'
      path: '/api/projects/$id/files'
      fullPath: '/api/projects/$id/files'
      preLoaderRoute: typeof ApiProjectsIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/analyze': {
      id: '/api/projects/$id/analyze'
      path: '/api/projects/$id/analyze'
      fullPath: '/api/projects/$id/analyze'
      preLoaderRoute: typeof ApiProjectsIdAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
  ApiJobsRunRoute: ApiJobsRunRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiProjectsIdAnalyzeRoute: ApiProjectsIdAnalyzeRoute,
  ApiProjectsIdFilesRoute: ApiProjectsIdFilesRoute,
  ApiProjectsIdImportRoute: ApiProjectsIdImportRoute,
  ApiProjectsIdVerifyRoute: ApiProjectsIdVerifyRoute,
  ApiProjectsIdIndexRoute: ApiProjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
