/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuickstartRouteImport } from './routes/quickstart'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as OwnerVisitorsRouteImport } from './routes/owner.visitors'
import { Route as OwnerUsersRouteImport } from './routes/owner.users'
import { Route as OwnerTenantsRouteImport } from './routes/owner.tenants'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerRolesRouteImport } from './routes/owner.roles'
import { Route as OwnerRecordsRouteImport } from './routes/owner.records'
import { Route as OwnerProjectsRouteImport } from './routes/owner.projects'
import { Route as OwnerJobsRouteImport } from './routes/owner.jobs'
import { Route as OwnerIntegrationsRouteImport } from './routes/owner.integrations'
import { Route as OwnerHealthRouteImport } from './routes/owner.health'
import { Route as OwnerFilesRouteImport } from './routes/owner.files'
import { Route as OwnerAuthRouteImport } from './routes/owner.auth'
import { Route as OwnerAuditLogsRouteImport } from './routes/owner.audit-logs'
import { Route as OwnerApiLogsRouteImport } from './routes/owner.api-logs'
import { Route as OwnerApiKeysRouteImport } from './routes/owner.api-keys'
import { Route as OwnerAlertsRouteImport } from './routes/owner.alerts'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardSitesDiscoverRouteImport } from './routes/dashboard.sites-discover'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSdkTestRouteImport } from './routes/dashboard.sdk-test'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard.records'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardHnDataRouteImport } from './routes/dashboard.hn-data'
import { Route as DashboardDocsRouteImport } from './routes/dashboard.docs'
import { Route as DashboardDatabasesRouteImport } from './routes/dashboard.databases'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBackupsRouteImport } from './routes/dashboard.backups'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTeamIndexRouteImport } from './routes/api/team/index'
import { Route as ApiTablesIndexRouteImport } from './routes/api/tables/index'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiBackupsIndexRouteImport } from './routes/api/backups/index'
import { Route as ApiApiKeysIndexRouteImport } from './routes/api/api-keys/index'
import { Route as OwnerProjectsSiteIdRouteImport } from './routes/owner.projects.$siteId'
import { Route as DashboardTablesIdRouteImport } from './routes/dashboard.tables.$id'
import { Route as ApiTablesIdRouteImport } from './routes/api/tables/$id'
import { Route as ApiSsoSignupRouteImport } from './routes/api/sso/signup'
import { Route as ApiSsoLoginRouteImport } from './routes/api/sso/login'
import { Route as ApiRecordsIdRouteImport } from './routes/api/records/$id'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'
import { Route as ApiJobsEnqueueRouteImport } from './routes/api/jobs/enqueue'
import { Route as ApiJobsDrainRouteImport } from './routes/api/jobs/drain'
import { Route as ApiHnRolesRouteImport } from './routes/api/hn/roles'
import { Route as ApiBillingUsageRouteImport } from './routes/api/billing/usage'
import { Route as ApiBillingPlansRouteImport } from './routes/api/billing/plans'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiApiKeysIdRouteImport } from './routes/api/api-keys/$id'
import { Route as ApiAdminVisitorsRouteImport } from './routes/api/admin/visitors'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminDbStatusRouteImport } from './routes/api/admin/db-status'
import { Route as ApiAdminAuditLogsRouteImport } from './routes/api/admin/audit-logs'
import { Route as ApiAdminApiLogsRouteImport } from './routes/api/admin/api-logs'
import { Route as ApiProjectsIdIndexRouteImport } from './routes/api/projects/$id/index'
import { Route as ApiHnStorageIndexRouteImport } from './routes/api/hn/storage/index'
import { Route as ApiHnSitesIndexRouteImport } from './routes/api/hn/sites/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiTablesIdRecordsRouteImport } from './routes/api/tables/$id/records'
import { Route as ApiTablesIdColumnsRouteImport } from './routes/api/tables/$id/columns'
import { Route as ApiPublicV1StorageRouteImport } from './routes/api/public/v1/storage'
import { Route as ApiPublicSsoVerifyRouteImport } from './routes/api/public/sso/verify'
import { Route as ApiPublicSsoMeRouteImport } from './routes/api/public/sso/me'
import { Route as ApiProjectsIdVerifyRouteImport } from './routes/api/projects/$id/verify'
import { Route as ApiProjectsIdImportRouteImport } from './routes/api/projects/$id/import'
import { Route as ApiProjectsIdAnalyzeRouteImport } from './routes/api/projects/$id/analyze'
import { Route as ApiHnStorageIdRouteImport } from './routes/api/hn/storage/$id'
import { Route as ApiHnSitesDiscoverRouteImport } from './routes/api/hn/sites/discover'
import { Route as ApiHnAuthSignupRouteImport } from './routes/api/hn/auth/signup'
import { Route as ApiHnAuthMeRouteImport } from './routes/api/hn/auth/me'
import { Route as ApiHnAuthLogoutRouteImport } from './routes/api/hn/auth/logout'
import { Route as ApiHnAuthLoginRouteImport } from './routes/api/hn/auth/login'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users.$id'
import { Route as ApiHnDbCollectionIndexRouteImport } from './routes/api/hn/db/$collection/index'
import { Route as ApiPublicV1StorageFileRouteImport } from './routes/api/public/v1/storage.file'
import { Route as ApiPublicV1DataCollectionRouteImport } from './routes/api/public/v1/data.$collection'
import { Route as ApiHnDbCollectionIdRouteImport } from './routes/api/hn/db/$collection/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickstartRoute = QuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVisitorsRoute = OwnerVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTenantsRoute = OwnerTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRolesRoute = OwnerRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRecordsRoute = OwnerRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProjectsRoute = OwnerProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerJobsRoute = OwnerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerIntegrationsRoute = OwnerIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHealthRoute = OwnerHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerFilesRoute = OwnerFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAuthRoute = OwnerAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAuditLogsRoute = OwnerAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerApiLogsRoute = OwnerApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerApiKeysRoute = OwnerApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAlertsRoute = OwnerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => OwnerRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSitesDiscoverRoute = DashboardSitesDiscoverRouteImport.update({
  id: '/sites-discover',
  path: '/sites-discover',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSdkTestRoute = DashboardSdkTestRouteImport.update({
  id: '/sdk-test',
  path: '/sdk-test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHnDataRoute = DashboardHnDataRouteImport.update({
  id: '/hn-data',
  path: '/hn-data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamIndexRoute = ApiTeamIndexRouteImport.update({
  id: '/api/team/',
  path: '/api/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTablesIndexRoute = ApiTablesIndexRouteImport.update({
  id: '/api/tables/',
  path: '/api/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupsIndexRoute = ApiBackupsIndexRouteImport.update({
  id: '/api/backups/',
  path: '/api/backups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIndexRoute = ApiApiKeysIndexRouteImport.update({
  id: '/api/api-keys/',
  path: '/api/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProjectsSiteIdRoute = OwnerProjectsSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => OwnerProjectsRoute,
} as any)
const DashboardTablesIdRoute = DashboardTablesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTablesRoute,
} as any)
const ApiTablesIdRoute = ApiTablesIdRouteImport.update({
  id: '/api/tables/$id',
  path: '/api/tables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoSignupRoute = ApiSsoSignupRouteImport.update({
  id: '/api/sso/signup',
  path: '/api/sso/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLoginRoute = ApiSsoLoginRouteImport.update({
  id: '/api/sso/login',
  path: '/api/sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsIdRoute = ApiRecordsIdRouteImport.update({
  id: '/api/records/$id',
  path: '/api/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsEnqueueRoute = ApiJobsEnqueueRouteImport.update({
  id: '/api/jobs/enqueue',
  path: '/api/jobs/enqueue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsDrainRoute = ApiJobsDrainRouteImport.update({
  id: '/api/jobs/drain',
  path: '/api/jobs/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnRolesRoute = ApiHnRolesRouteImport.update({
  id: '/api/hn/roles',
  path: '/api/hn/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingUsageRoute = ApiBillingUsageRouteImport.update({
  id: '/api/billing/usage',
  path: '/api/billing/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlansRoute = ApiBillingPlansRouteImport.update({
  id: '/api/billing/plans',
  path: '/api/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIdRoute = ApiApiKeysIdRouteImport.update({
  id: '/api/api-keys/$id',
  path: '/api/api-keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVisitorsRoute = ApiAdminVisitorsRouteImport.update({
  id: '/api/admin/visitors',
  path: '/api/admin/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDbStatusRoute = ApiAdminDbStatusRouteImport.update({
  id: '/api/admin/db-status',
  path: '/api/admin/db-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditLogsRoute = ApiAdminAuditLogsRouteImport.update({
  id: '/api/admin/audit-logs',
  path: '/api/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApiLogsRoute = ApiAdminApiLogsRouteImport.update({
  id: '/api/admin/api-logs',
  path: '/api/admin/api-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdIndexRoute = ApiProjectsIdIndexRouteImport.update({
  id: '/api/projects/$id/',
  path: '/api/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnStorageIndexRoute = ApiHnStorageIndexRouteImport.update({
  id: '/api/hn/storage/',
  path: '/api/hn/storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnSitesIndexRoute = ApiHnSitesIndexRouteImport.update({
  id: '/api/hn/sites/',
  path: '/api/hn/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTablesIdRecordsRoute = ApiTablesIdRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => ApiTablesIdRoute,
} as any)
const ApiTablesIdColumnsRoute = ApiTablesIdColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => ApiTablesIdRoute,
} as any)
const ApiPublicV1StorageRoute = ApiPublicV1StorageRouteImport.update({
  id: '/api/public/v1/storage',
  path: '/api/public/v1/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSsoVerifyRoute = ApiPublicSsoVerifyRouteImport.update({
  id: '/api/public/sso/verify',
  path: '/api/public/sso/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSsoMeRoute = ApiPublicSsoMeRouteImport.update({
  id: '/api/public/sso/me',
  path: '/api/public/sso/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdVerifyRoute = ApiProjectsIdVerifyRouteImport.update({
  id: '/api/projects/$id/verify',
  path: '/api/projects/$id/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdImportRoute = ApiProjectsIdImportRouteImport.update({
  id: '/api/projects/$id/import',
  path: '/api/projects/$id/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdAnalyzeRoute = ApiProjectsIdAnalyzeRouteImport.update({
  id: '/api/projects/$id/analyze',
  path: '/api/projects/$id/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnStorageIdRoute = ApiHnStorageIdRouteImport.update({
  id: '/api/hn/storage/$id',
  path: '/api/hn/storage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnSitesDiscoverRoute = ApiHnSitesDiscoverRouteImport.update({
  id: '/api/hn/sites/discover',
  path: '/api/hn/sites/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnAuthSignupRoute = ApiHnAuthSignupRouteImport.update({
  id: '/api/hn/auth/signup',
  path: '/api/hn/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnAuthMeRoute = ApiHnAuthMeRouteImport.update({
  id: '/api/hn/auth/me',
  path: '/api/hn/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnAuthLogoutRoute = ApiHnAuthLogoutRouteImport.update({
  id: '/api/hn/auth/logout',
  path: '/api/hn/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHnAuthLoginRoute = ApiHnAuthLoginRouteImport.update({
  id: '/api/hn/auth/login',
  path: '/api/hn/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiHnDbCollectionIndexRoute = ApiHnDbCollectionIndexRouteImport.update({
  id: '/api/hn/db/$collection/',
  path: '/api/hn/db/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StorageFileRoute = ApiPublicV1StorageFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiPublicV1StorageRoute,
} as any)
const ApiPublicV1DataCollectionRoute =
  ApiPublicV1DataCollectionRouteImport.update({
    id: '/api/public/v1/data/$collection',
    path: '/api/public/v1/data/$collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHnDbCollectionIdRoute = ApiHnDbCollectionIdRouteImport.update({
  id: '/api/hn/db/$collection/$id',
  path: '/api/hn/db/$collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/quickstart': typeof QuickstartRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/hn-data': typeof DashboardHnDataRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/sdk-test': typeof DashboardSdkTestRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sites-discover': typeof DashboardSitesDiscoverRoute
  '/dashboard/tables': typeof DashboardTablesRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/api-keys': typeof OwnerApiKeysRoute
  '/owner/api-logs': typeof OwnerApiLogsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/auth': typeof OwnerAuthRoute
  '/owner/files': typeof OwnerFilesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/projects': typeof OwnerProjectsRouteWithChildren
  '/owner/records': typeof OwnerRecordsRoute
  '/owner/roles': typeof OwnerRolesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tenants': typeof OwnerTenantsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/api/admin/api-logs': typeof ApiAdminApiLogsRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/db-status': typeof ApiAdminDbStatusRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/admin/visitors': typeof ApiAdminVisitorsRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/usage': typeof ApiBillingUsageRoute
  '/api/hn/roles': typeof ApiHnRolesRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/records/$id': typeof ApiRecordsIdRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/signup': typeof ApiSsoSignupRoute
  '/api/tables/$id': typeof ApiTablesIdRouteWithChildren
  '/dashboard/tables/$id': typeof DashboardTablesIdRoute
  '/owner/projects/$siteId': typeof OwnerProjectsSiteIdRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/backups/': typeof ApiBackupsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/tables/': typeof ApiTablesIndexRoute
  '/api/team/': typeof ApiTeamIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/hn/auth/login': typeof ApiHnAuthLoginRoute
  '/api/hn/auth/logout': typeof ApiHnAuthLogoutRoute
  '/api/hn/auth/me': typeof ApiHnAuthMeRoute
  '/api/hn/auth/signup': typeof ApiHnAuthSignupRoute
  '/api/hn/sites/discover': typeof ApiHnSitesDiscoverRoute
  '/api/hn/storage/$id': typeof ApiHnStorageIdRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/public/sso/me': typeof ApiPublicSsoMeRoute
  '/api/public/sso/verify': typeof ApiPublicSsoVerifyRoute
  '/api/public/v1/storage': typeof ApiPublicV1StorageRouteWithChildren
  '/api/tables/$id/columns': typeof ApiTablesIdColumnsRoute
  '/api/tables/$id/records': typeof ApiTablesIdRecordsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/hn/sites/': typeof ApiHnSitesIndexRoute
  '/api/hn/storage/': typeof ApiHnStorageIndexRoute
  '/api/projects/$id/': typeof ApiProjectsIdIndexRoute
  '/api/hn/db/$collection/$id': typeof ApiHnDbCollectionIdRoute
  '/api/public/v1/data/$collection': typeof ApiPublicV1DataCollectionRoute
  '/api/public/v1/storage/file': typeof ApiPublicV1StorageFileRoute
  '/api/hn/db/$collection/': typeof ApiHnDbCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quickstart': typeof QuickstartRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/hn-data': typeof DashboardHnDataRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/sdk-test': typeof DashboardSdkTestRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sites-discover': typeof DashboardSitesDiscoverRoute
  '/dashboard/tables': typeof DashboardTablesRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/api-keys': typeof OwnerApiKeysRoute
  '/owner/api-logs': typeof OwnerApiLogsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/auth': typeof OwnerAuthRoute
  '/owner/files': typeof OwnerFilesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/projects': typeof OwnerProjectsRouteWithChildren
  '/owner/records': typeof OwnerRecordsRoute
  '/owner/roles': typeof OwnerRolesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tenants': typeof OwnerTenantsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/api/admin/api-logs': typeof ApiAdminApiLogsRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/db-status': typeof ApiAdminDbStatusRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/admin/visitors': typeof ApiAdminVisitorsRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/usage': typeof ApiBillingUsageRoute
  '/api/hn/roles': typeof ApiHnRolesRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/records/$id': typeof ApiRecordsIdRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/signup': typeof ApiSsoSignupRoute
  '/api/tables/$id': typeof ApiTablesIdRouteWithChildren
  '/dashboard/tables/$id': typeof DashboardTablesIdRoute
  '/owner/projects/$siteId': typeof OwnerProjectsSiteIdRoute
  '/api/api-keys': typeof ApiApiKeysIndexRoute
  '/api/backups': typeof ApiBackupsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/tables': typeof ApiTablesIndexRoute
  '/api/team': typeof ApiTeamIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/hn/auth/login': typeof ApiHnAuthLoginRoute
  '/api/hn/auth/logout': typeof ApiHnAuthLogoutRoute
  '/api/hn/auth/me': typeof ApiHnAuthMeRoute
  '/api/hn/auth/signup': typeof ApiHnAuthSignupRoute
  '/api/hn/sites/discover': typeof ApiHnSitesDiscoverRoute
  '/api/hn/storage/$id': typeof ApiHnStorageIdRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/public/sso/me': typeof ApiPublicSsoMeRoute
  '/api/public/sso/verify': typeof ApiPublicSsoVerifyRoute
  '/api/public/v1/storage': typeof ApiPublicV1StorageRouteWithChildren
  '/api/tables/$id/columns': typeof ApiTablesIdColumnsRoute
  '/api/tables/$id/records': typeof ApiTablesIdRecordsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/hn/sites': typeof ApiHnSitesIndexRoute
  '/api/hn/storage': typeof ApiHnStorageIndexRoute
  '/api/projects/$id': typeof ApiProjectsIdIndexRoute
  '/api/hn/db/$collection/$id': typeof ApiHnDbCollectionIdRoute
  '/api/public/v1/data/$collection': typeof ApiPublicV1DataCollectionRoute
  '/api/public/v1/storage/file': typeof ApiPublicV1StorageFileRoute
  '/api/hn/db/$collection': typeof ApiHnDbCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/quickstart': typeof QuickstartRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/hn-data': typeof DashboardHnDataRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/sdk-test': typeof DashboardSdkTestRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sites-discover': typeof DashboardSitesDiscoverRoute
  '/dashboard/tables': typeof DashboardTablesRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/api-keys': typeof OwnerApiKeysRoute
  '/owner/api-logs': typeof OwnerApiLogsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/auth': typeof OwnerAuthRoute
  '/owner/files': typeof OwnerFilesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/projects': typeof OwnerProjectsRouteWithChildren
  '/owner/records': typeof OwnerRecordsRoute
  '/owner/roles': typeof OwnerRolesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tenants': typeof OwnerTenantsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/owner/visitors': typeof OwnerVisitorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/api/admin/api-logs': typeof ApiAdminApiLogsRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/db-status': typeof ApiAdminDbStatusRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/admin/visitors': typeof ApiAdminVisitorsRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/usage': typeof ApiBillingUsageRoute
  '/api/hn/roles': typeof ApiHnRolesRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/records/$id': typeof ApiRecordsIdRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/signup': typeof ApiSsoSignupRoute
  '/api/tables/$id': typeof ApiTablesIdRouteWithChildren
  '/dashboard/tables/$id': typeof DashboardTablesIdRoute
  '/owner/projects/$siteId': typeof OwnerProjectsSiteIdRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/backups/': typeof ApiBackupsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/tables/': typeof ApiTablesIndexRoute
  '/api/team/': typeof ApiTeamIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/hn/auth/login': typeof ApiHnAuthLoginRoute
  '/api/hn/auth/logout': typeof ApiHnAuthLogoutRoute
  '/api/hn/auth/me': typeof ApiHnAuthMeRoute
  '/api/hn/auth/signup': typeof ApiHnAuthSignupRoute
  '/api/hn/sites/discover': typeof ApiHnSitesDiscoverRoute
  '/api/hn/storage/$id': typeof ApiHnStorageIdRoute
  '/api/projects/$id/analyze': typeof ApiProjectsIdAnalyzeRoute
  '/api/projects/$id/import': typeof ApiProjectsIdImportRoute
  '/api/projects/$id/verify': typeof ApiProjectsIdVerifyRoute
  '/api/public/sso/me': typeof ApiPublicSsoMeRoute
  '/api/public/sso/verify': typeof ApiPublicSsoVerifyRoute
  '/api/public/v1/storage': typeof ApiPublicV1StorageRouteWithChildren
  '/api/tables/$id/columns': typeof ApiTablesIdColumnsRoute
  '/api/tables/$id/records': typeof ApiTablesIdRecordsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/hn/sites/': typeof ApiHnSitesIndexRoute
  '/api/hn/storage/': typeof ApiHnStorageIndexRoute
  '/api/projects/$id/': typeof ApiProjectsIdIndexRoute
  '/api/hn/db/$collection/$id': typeof ApiHnDbCollectionIdRoute
  '/api/public/v1/data/$collection': typeof ApiPublicV1DataCollectionRoute
  '/api/public/v1/storage/file': typeof ApiPublicV1StorageFileRoute
  '/api/hn/db/$collection/': typeof ApiHnDbCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/owner'
    | '/quickstart'
    | '/signup'
    | '/api/health'
    | '/dashboard/api-keys'
    | '/dashboard/backups'
    | '/dashboard/billing'
    | '/dashboard/databases'
    | '/dashboard/docs'
    | '/dashboard/hn-data'
    | '/dashboard/logs'
    | '/dashboard/records'
    | '/dashboard/sdk-test'
    | '/dashboard/settings'
    | '/dashboard/sites-discover'
    | '/dashboard/tables'
    | '/dashboard/team'
    | '/owner/alerts'
    | '/owner/api-keys'
    | '/owner/api-logs'
    | '/owner/audit-logs'
    | '/owner/auth'
    | '/owner/files'
    | '/owner/health'
    | '/owner/integrations'
    | '/owner/jobs'
    | '/owner/projects'
    | '/owner/records'
    | '/owner/roles'
    | '/owner/settings'
    | '/owner/tenants'
    | '/owner/users'
    | '/owner/visitors'
    | '/projects/$id'
    | '/dashboard/'
    | '/owner/'
    | '/api/admin/api-logs'
    | '/api/admin/audit-logs'
    | '/api/admin/db-status'
    | '/api/admin/users'
    | '/api/admin/visitors'
    | '/api/api-keys/$id'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/billing/plans'
    | '/api/billing/usage'
    | '/api/hn/roles'
    | '/api/jobs/drain'
    | '/api/jobs/enqueue'
    | '/api/public/analytics'
    | '/api/public/config'
    | '/api/records/$id'
    | '/api/sso/login'
    | '/api/sso/signup'
    | '/api/tables/$id'
    | '/dashboard/tables/$id'
    | '/owner/projects/$siteId'
    | '/api/api-keys/'
    | '/api/backups/'
    | '/api/projects/'
    | '/api/tables/'
    | '/api/team/'
    | '/api/admin/users/$id'
    | '/api/hn/auth/login'
    | '/api/hn/auth/logout'
    | '/api/hn/auth/me'
    | '/api/hn/auth/signup'
    | '/api/hn/sites/discover'
    | '/api/hn/storage/$id'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/public/sso/me'
    | '/api/public/sso/verify'
    | '/api/public/v1/storage'
    | '/api/tables/$id/columns'
    | '/api/tables/$id/records'
    | '/lovable/email/queue/process'
    | '/api/hn/sites/'
    | '/api/hn/storage/'
    | '/api/projects/$id/'
    | '/api/hn/db/$collection/$id'
    | '/api/public/v1/data/$collection'
    | '/api/public/v1/storage/file'
    | '/api/hn/db/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/quickstart'
    | '/signup'
    | '/api/health'
    | '/dashboard/api-keys'
    | '/dashboard/backups'
    | '/dashboard/billing'
    | '/dashboard/databases'
    | '/dashboard/docs'
    | '/dashboard/hn-data'
    | '/dashboard/logs'
    | '/dashboard/records'
    | '/dashboard/sdk-test'
    | '/dashboard/settings'
    | '/dashboard/sites-discover'
    | '/dashboard/tables'
    | '/dashboard/team'
    | '/owner/alerts'
    | '/owner/api-keys'
    | '/owner/api-logs'
    | '/owner/audit-logs'
    | '/owner/auth'
    | '/owner/files'
    | '/owner/health'
    | '/owner/integrations'
    | '/owner/jobs'
    | '/owner/projects'
    | '/owner/records'
    | '/owner/roles'
    | '/owner/settings'
    | '/owner/tenants'
    | '/owner/users'
    | '/owner/visitors'
    | '/projects/$id'
    | '/dashboard'
    | '/owner'
    | '/api/admin/api-logs'
    | '/api/admin/audit-logs'
    | '/api/admin/db-status'
    | '/api/admin/users'
    | '/api/admin/visitors'
    | '/api/api-keys/$id'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/billing/plans'
    | '/api/billing/usage'
    | '/api/hn/roles'
    | '/api/jobs/drain'
    | '/api/jobs/enqueue'
    | '/api/public/analytics'
    | '/api/public/config'
    | '/api/records/$id'
    | '/api/sso/login'
    | '/api/sso/signup'
    | '/api/tables/$id'
    | '/dashboard/tables/$id'
    | '/owner/projects/$siteId'
    | '/api/api-keys'
    | '/api/backups'
    | '/api/projects'
    | '/api/tables'
    | '/api/team'
    | '/api/admin/users/$id'
    | '/api/hn/auth/login'
    | '/api/hn/auth/logout'
    | '/api/hn/auth/me'
    | '/api/hn/auth/signup'
    | '/api/hn/sites/discover'
    | '/api/hn/storage/$id'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/public/sso/me'
    | '/api/public/sso/verify'
    | '/api/public/v1/storage'
    | '/api/tables/$id/columns'
    | '/api/tables/$id/records'
    | '/lovable/email/queue/process'
    | '/api/hn/sites'
    | '/api/hn/storage'
    | '/api/projects/$id'
    | '/api/hn/db/$collection/$id'
    | '/api/public/v1/data/$collection'
    | '/api/public/v1/storage/file'
    | '/api/hn/db/$collection'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/owner'
    | '/quickstart'
    | '/signup'
    | '/api/health'
    | '/dashboard/api-keys'
    | '/dashboard/backups'
    | '/dashboard/billing'
    | '/dashboard/databases'
    | '/dashboard/docs'
    | '/dashboard/hn-data'
    | '/dashboard/logs'
    | '/dashboard/records'
    | '/dashboard/sdk-test'
    | '/dashboard/settings'
    | '/dashboard/sites-discover'
    | '/dashboard/tables'
    | '/dashboard/team'
    | '/owner/alerts'
    | '/owner/api-keys'
    | '/owner/api-logs'
    | '/owner/audit-logs'
    | '/owner/auth'
    | '/owner/files'
    | '/owner/health'
    | '/owner/integrations'
    | '/owner/jobs'
    | '/owner/projects'
    | '/owner/records'
    | '/owner/roles'
    | '/owner/settings'
    | '/owner/tenants'
    | '/owner/users'
    | '/owner/visitors'
    | '/projects/$id'
    | '/dashboard/'
    | '/owner/'
    | '/api/admin/api-logs'
    | '/api/admin/audit-logs'
    | '/api/admin/db-status'
    | '/api/admin/users'
    | '/api/admin/visitors'
    | '/api/api-keys/$id'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/billing/plans'
    | '/api/billing/usage'
    | '/api/hn/roles'
    | '/api/jobs/drain'
    | '/api/jobs/enqueue'
    | '/api/public/analytics'
    | '/api/public/config'
    | '/api/records/$id'
    | '/api/sso/login'
    | '/api/sso/signup'
    | '/api/tables/$id'
    | '/dashboard/tables/$id'
    | '/owner/projects/$siteId'
    | '/api/api-keys/'
    | '/api/backups/'
    | '/api/projects/'
    | '/api/tables/'
    | '/api/team/'
    | '/api/admin/users/$id'
    | '/api/hn/auth/login'
    | '/api/hn/auth/logout'
    | '/api/hn/auth/me'
    | '/api/hn/auth/signup'
    | '/api/hn/sites/discover'
    | '/api/hn/storage/$id'
    | '/api/projects/$id/analyze'
    | '/api/projects/$id/import'
    | '/api/projects/$id/verify'
    | '/api/public/sso/me'
    | '/api/public/sso/verify'
    | '/api/public/v1/storage'
    | '/api/tables/$id/columns'
    | '/api/tables/$id/records'
    | '/lovable/email/queue/process'
    | '/api/hn/sites/'
    | '/api/hn/storage/'
    | '/api/projects/$id/'
    | '/api/hn/db/$collection/$id'
    | '/api/public/v1/data/$collection'
    | '/api/public/v1/storage/file'
    | '/api/hn/db/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  QuickstartRoute: typeof QuickstartRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiAdminApiLogsRoute: typeof ApiAdminApiLogsRoute
  ApiAdminAuditLogsRoute: typeof ApiAdminAuditLogsRoute
  ApiAdminDbStatusRoute: typeof ApiAdminDbStatusRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAdminVisitorsRoute: typeof ApiAdminVisitorsRoute
  ApiApiKeysIdRoute: typeof ApiApiKeysIdRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiBillingPlansRoute: typeof ApiBillingPlansRoute
  ApiBillingUsageRoute: typeof ApiBillingUsageRoute
  ApiHnRolesRoute: typeof ApiHnRolesRoute
  ApiJobsDrainRoute: typeof ApiJobsDrainRoute
  ApiJobsEnqueueRoute: typeof ApiJobsEnqueueRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiRecordsIdRoute: typeof ApiRecordsIdRoute
  ApiSsoLoginRoute: typeof ApiSsoLoginRoute
  ApiSsoSignupRoute: typeof ApiSsoSignupRoute
  ApiTablesIdRoute: typeof ApiTablesIdRouteWithChildren
  ApiApiKeysIndexRoute: typeof ApiApiKeysIndexRoute
  ApiBackupsIndexRoute: typeof ApiBackupsIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiTablesIndexRoute: typeof ApiTablesIndexRoute
  ApiTeamIndexRoute: typeof ApiTeamIndexRoute
  ApiHnAuthLoginRoute: typeof ApiHnAuthLoginRoute
  ApiHnAuthLogoutRoute: typeof ApiHnAuthLogoutRoute
  ApiHnAuthMeRoute: typeof ApiHnAuthMeRoute
  ApiHnAuthSignupRoute: typeof ApiHnAuthSignupRoute
  ApiHnSitesDiscoverRoute: typeof ApiHnSitesDiscoverRoute
  ApiHnStorageIdRoute: typeof ApiHnStorageIdRoute
  ApiProjectsIdAnalyzeRoute: typeof ApiProjectsIdAnalyzeRoute
  ApiProjectsIdImportRoute: typeof ApiProjectsIdImportRoute
  ApiProjectsIdVerifyRoute: typeof ApiProjectsIdVerifyRoute
  ApiPublicSsoMeRoute: typeof ApiPublicSsoMeRoute
  ApiPublicSsoVerifyRoute: typeof ApiPublicSsoVerifyRoute
  ApiPublicV1StorageRoute: typeof ApiPublicV1StorageRouteWithChildren
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiHnSitesIndexRoute: typeof ApiHnSitesIndexRoute
  ApiHnStorageIndexRoute: typeof ApiHnStorageIndexRoute
  ApiProjectsIdIndexRoute: typeof ApiProjectsIdIndexRoute
  ApiHnDbCollectionIdRoute: typeof ApiHnDbCollectionIdRoute
  ApiPublicV1DataCollectionRoute: typeof ApiPublicV1DataCollectionRoute
  ApiHnDbCollectionIndexRoute: typeof ApiHnDbCollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickstart': {
      id: '/quickstart'
      path: '/quickstart'
      fullPath: '/quickstart'
      preLoaderRoute: typeof QuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/visitors': {
      id: '/owner/visitors'
      path: '/visitors'
      fullPath: '/owner/visitors'
      preLoaderRoute: typeof OwnerVisitorsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/users': {
      id: '/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tenants': {
      id: '/owner/tenants'
      path: '/tenants'
      fullPath: '/owner/tenants'
      preLoaderRoute: typeof OwnerTenantsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/roles': {
      id: '/owner/roles'
      path: '/roles'
      fullPath: '/owner/roles'
      preLoaderRoute: typeof OwnerRolesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/records': {
      id: '/owner/records'
      path: '/records'
      fullPath: '/owner/records'
      preLoaderRoute: typeof OwnerRecordsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/projects': {
      id: '/owner/projects'
      path: '/projects'
      fullPath: '/owner/projects'
      preLoaderRoute: typeof OwnerProjectsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/jobs': {
      id: '/owner/jobs'
      path: '/jobs'
      fullPath: '/owner/jobs'
      preLoaderRoute: typeof OwnerJobsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/integrations': {
      id: '/owner/integrations'
      path: '/integrations'
      fullPath: '/owner/integrations'
      preLoaderRoute: typeof OwnerIntegrationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/health': {
      id: '/owner/health'
      path: '/health'
      fullPath: '/owner/health'
      preLoaderRoute: typeof OwnerHealthRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/files': {
      id: '/owner/files'
      path: '/files'
      fullPath: '/owner/files'
      preLoaderRoute: typeof OwnerFilesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/auth': {
      id: '/owner/auth'
      path: '/auth'
      fullPath: '/owner/auth'
      preLoaderRoute: typeof OwnerAuthRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/audit-logs': {
      id: '/owner/audit-logs'
      path: '/audit-logs'
      fullPath: '/owner/audit-logs'
      preLoaderRoute: typeof OwnerAuditLogsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/api-logs': {
      id: '/owner/api-logs'
      path: '/api-logs'
      fullPath: '/owner/api-logs'
      preLoaderRoute: typeof OwnerApiLogsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/api-keys': {
      id: '/owner/api-keys'
      path: '/api-keys'
      fullPath: '/owner/api-keys'
      preLoaderRoute: typeof OwnerApiKeysRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/alerts': {
      id: '/owner/alerts'
      path: '/alerts'
      fullPath: '/owner/alerts'
      preLoaderRoute: typeof OwnerAlertsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sites-discover': {
      id: '/dashboard/sites-discover'
      path: '/sites-discover'
      fullPath: '/dashboard/sites-discover'
      preLoaderRoute: typeof DashboardSitesDiscoverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sdk-test': {
      id: '/dashboard/sdk-test'
      path: '/sdk-test'
      fullPath: '/dashboard/sdk-test'
      preLoaderRoute: typeof DashboardSdkTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hn-data': {
      id: '/dashboard/hn-data'
      path: '/hn-data'
      fullPath: '/dashboard/hn-data'
      preLoaderRoute: typeof DashboardHnDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs': {
      id: '/dashboard/docs'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/databases': {
      id: '/dashboard/databases'
      path: '/databases'
      fullPath: '/dashboard/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backups': {
      id: '/dashboard/backups'
      path: '/backups'
      fullPath: '/dashboard/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/': {
      id: '/api/team/'
      path: '/api/team'
      fullPath: '/api/team/'
      preLoaderRoute: typeof ApiTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables/': {
      id: '/api/tables/'
      path: '/api/tables'
      fullPath: '/api/tables/'
      preLoaderRoute: typeof ApiTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backups/': {
      id: '/api/backups/'
      path: '/api/backups'
      fullPath: '/api/backups/'
      preLoaderRoute: typeof ApiBackupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/': {
      id: '/api/api-keys/'
      path: '/api/api-keys'
      fullPath: '/api/api-keys/'
      preLoaderRoute: typeof ApiApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/projects/$siteId': {
      id: '/owner/projects/$siteId'
      path: '/$siteId'
      fullPath: '/owner/projects/$siteId'
      preLoaderRoute: typeof OwnerProjectsSiteIdRouteImport
      parentRoute: typeof OwnerProjectsRoute
    }
    '/dashboard/tables/$id': {
      id: '/dashboard/tables/$id'
      path: '/$id'
      fullPath: '/dashboard/tables/$id'
      preLoaderRoute: typeof DashboardTablesIdRouteImport
      parentRoute: typeof DashboardTablesRoute
    }
    '/api/tables/$id': {
      id: '/api/tables/$id'
      path: '/api/tables/$id'
      fullPath: '/api/tables/$id'
      preLoaderRoute: typeof ApiTablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/signup': {
      id: '/api/sso/signup'
      path: '/api/sso/signup'
      fullPath: '/api/sso/signup'
      preLoaderRoute: typeof ApiSsoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/login': {
      id: '/api/sso/login'
      path: '/api/sso/login'
      fullPath: '/api/sso/login'
      preLoaderRoute: typeof ApiSsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$id': {
      id: '/api/records/$id'
      path: '/api/records/$id'
      fullPath: '/api/records/$id'
      preLoaderRoute: typeof ApiRecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/enqueue': {
      id: '/api/jobs/enqueue'
      path: '/api/jobs/enqueue'
      fullPath: '/api/jobs/enqueue'
      preLoaderRoute: typeof ApiJobsEnqueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/drain': {
      id: '/api/jobs/drain'
      path: '/api/jobs/drain'
      fullPath: '/api/jobs/drain'
      preLoaderRoute: typeof ApiJobsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/roles': {
      id: '/api/hn/roles'
      path: '/api/hn/roles'
      fullPath: '/api/hn/roles'
      preLoaderRoute: typeof ApiHnRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/usage': {
      id: '/api/billing/usage'
      path: '/api/billing/usage'
      fullPath: '/api/billing/usage'
      preLoaderRoute: typeof ApiBillingUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plans': {
      id: '/api/billing/plans'
      path: '/api/billing/plans'
      fullPath: '/api/billing/plans'
      preLoaderRoute: typeof ApiBillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$id': {
      id: '/api/api-keys/$id'
      path: '/api/api-keys/$id'
      fullPath: '/api/api-keys/$id'
      preLoaderRoute: typeof ApiApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/visitors': {
      id: '/api/admin/visitors'
      path: '/api/admin/visitors'
      fullPath: '/api/admin/visitors'
      preLoaderRoute: typeof ApiAdminVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/db-status': {
      id: '/api/admin/db-status'
      path: '/api/admin/db-status'
      fullPath: '/api/admin/db-status'
      preLoaderRoute: typeof ApiAdminDbStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-logs': {
      id: '/api/admin/audit-logs'
      path: '/api/admin/audit-logs'
      fullPath: '/api/admin/audit-logs'
      preLoaderRoute: typeof ApiAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/api-logs': {
      id: '/api/admin/api-logs'
      path: '/api/admin/api-logs'
      fullPath: '/api/admin/api-logs'
      preLoaderRoute: typeof ApiAdminApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/': {
      id: '/api/projects/$id/'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id/'
      preLoaderRoute: typeof ApiProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/storage/': {
      id: '/api/hn/storage/'
      path: '/api/hn/storage'
      fullPath: '/api/hn/storage/'
      preLoaderRoute: typeof ApiHnStorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/sites/': {
      id: '/api/hn/sites/'
      path: '/api/hn/sites'
      fullPath: '/api/hn/sites/'
      preLoaderRoute: typeof ApiHnSitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables/$id/records': {
      id: '/api/tables/$id/records'
      path: '/records'
      fullPath: '/api/tables/$id/records'
      preLoaderRoute: typeof ApiTablesIdRecordsRouteImport
      parentRoute: typeof ApiTablesIdRoute
    }
    '/api/tables/$id/columns': {
      id: '/api/tables/$id/columns'
      path: '/columns'
      fullPath: '/api/tables/$id/columns'
      preLoaderRoute: typeof ApiTablesIdColumnsRouteImport
      parentRoute: typeof ApiTablesIdRoute
    }
    '/api/public/v1/storage': {
      id: '/api/public/v1/storage'
      path: '/api/public/v1/storage'
      fullPath: '/api/public/v1/storage'
      preLoaderRoute: typeof ApiPublicV1StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sso/verify': {
      id: '/api/public/sso/verify'
      path: '/api/public/sso/verify'
      fullPath: '/api/public/sso/verify'
      preLoaderRoute: typeof ApiPublicSsoVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sso/me': {
      id: '/api/public/sso/me'
      path: '/api/public/sso/me'
      fullPath: '/api/public/sso/me'
      preLoaderRoute: typeof ApiPublicSsoMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/verify': {
      id: '/api/projects/$id/verify'
      path: '/api/projects/$id/verify'
      fullPath: '/api/projects/$id/verify'
      preLoaderRoute: typeof ApiProjectsIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/import': {
      id: '/api/projects/$id/import'
      path: '/api/projects/$id/import'
      fullPath: '/api/projects/$id/import'
      preLoaderRoute: typeof ApiProjectsIdImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/analyze': {
      id: '/api/projects/$id/analyze'
      path: '/api/projects/$id/analyze'
      fullPath: '/api/projects/$id/analyze'
      preLoaderRoute: typeof ApiProjectsIdAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/storage/$id': {
      id: '/api/hn/storage/$id'
      path: '/api/hn/storage/$id'
      fullPath: '/api/hn/storage/$id'
      preLoaderRoute: typeof ApiHnStorageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/sites/discover': {
      id: '/api/hn/sites/discover'
      path: '/api/hn/sites/discover'
      fullPath: '/api/hn/sites/discover'
      preLoaderRoute: typeof ApiHnSitesDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/auth/signup': {
      id: '/api/hn/auth/signup'
      path: '/api/hn/auth/signup'
      fullPath: '/api/hn/auth/signup'
      preLoaderRoute: typeof ApiHnAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/auth/me': {
      id: '/api/hn/auth/me'
      path: '/api/hn/auth/me'
      fullPath: '/api/hn/auth/me'
      preLoaderRoute: typeof ApiHnAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/auth/logout': {
      id: '/api/hn/auth/logout'
      path: '/api/hn/auth/logout'
      fullPath: '/api/hn/auth/logout'
      preLoaderRoute: typeof ApiHnAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/auth/login': {
      id: '/api/hn/auth/login'
      path: '/api/hn/auth/login'
      fullPath: '/api/hn/auth/login'
      preLoaderRoute: typeof ApiHnAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/hn/db/$collection/': {
      id: '/api/hn/db/$collection/'
      path: '/api/hn/db/$collection'
      fullPath: '/api/hn/db/$collection/'
      preLoaderRoute: typeof ApiHnDbCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/storage/file': {
      id: '/api/public/v1/storage/file'
      path: '/file'
      fullPath: '/api/public/v1/storage/file'
      preLoaderRoute: typeof ApiPublicV1StorageFileRouteImport
      parentRoute: typeof ApiPublicV1StorageRoute
    }
    '/api/public/v1/data/$collection': {
      id: '/api/public/v1/data/$collection'
      path: '/api/public/v1/data/$collection'
      fullPath: '/api/public/v1/data/$collection'
      preLoaderRoute: typeof ApiPublicV1DataCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hn/db/$collection/$id': {
      id: '/api/hn/db/$collection/$id'
      path: '/api/hn/db/$collection/$id'
      fullPath: '/api/hn/db/$collection/$id'
      preLoaderRoute: typeof ApiHnDbCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardTablesRouteChildren {
  DashboardTablesIdRoute: typeof DashboardTablesIdRoute
}

const DashboardTablesRouteChildren: DashboardTablesRouteChildren = {
  DashboardTablesIdRoute: DashboardTablesIdRoute,
}

const DashboardTablesRouteWithChildren = DashboardTablesRoute._addFileChildren(
  DashboardTablesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardBackupsRoute: typeof DashboardBackupsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDatabasesRoute: typeof DashboardDatabasesRoute
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardHnDataRoute: typeof DashboardHnDataRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardSdkTestRoute: typeof DashboardSdkTestRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSitesDiscoverRoute: typeof DashboardSitesDiscoverRoute
  DashboardTablesRoute: typeof DashboardTablesRouteWithChildren
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardBackupsRoute: DashboardBackupsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDatabasesRoute: DashboardDatabasesRoute,
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardHnDataRoute: DashboardHnDataRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardSdkTestRoute: DashboardSdkTestRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSitesDiscoverRoute: DashboardSitesDiscoverRoute,
  DashboardTablesRoute: DashboardTablesRouteWithChildren,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OwnerProjectsRouteChildren {
  OwnerProjectsSiteIdRoute: typeof OwnerProjectsSiteIdRoute
}

const OwnerProjectsRouteChildren: OwnerProjectsRouteChildren = {
  OwnerProjectsSiteIdRoute: OwnerProjectsSiteIdRoute,
}

const OwnerProjectsRouteWithChildren = OwnerProjectsRoute._addFileChildren(
  OwnerProjectsRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAlertsRoute: typeof OwnerAlertsRoute
  OwnerApiKeysRoute: typeof OwnerApiKeysRoute
  OwnerApiLogsRoute: typeof OwnerApiLogsRoute
  OwnerAuditLogsRoute: typeof OwnerAuditLogsRoute
  OwnerAuthRoute: typeof OwnerAuthRoute
  OwnerFilesRoute: typeof OwnerFilesRoute
  OwnerHealthRoute: typeof OwnerHealthRoute
  OwnerIntegrationsRoute: typeof OwnerIntegrationsRoute
  OwnerJobsRoute: typeof OwnerJobsRoute
  OwnerProjectsRoute: typeof OwnerProjectsRouteWithChildren
  OwnerRecordsRoute: typeof OwnerRecordsRoute
  OwnerRolesRoute: typeof OwnerRolesRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerTenantsRoute: typeof OwnerTenantsRoute
  OwnerUsersRoute: typeof OwnerUsersRoute
  OwnerVisitorsRoute: typeof OwnerVisitorsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAlertsRoute: OwnerAlertsRoute,
  OwnerApiKeysRoute: OwnerApiKeysRoute,
  OwnerApiLogsRoute: OwnerApiLogsRoute,
  OwnerAuditLogsRoute: OwnerAuditLogsRoute,
  OwnerAuthRoute: OwnerAuthRoute,
  OwnerFilesRoute: OwnerFilesRoute,
  OwnerHealthRoute: OwnerHealthRoute,
  OwnerIntegrationsRoute: OwnerIntegrationsRoute,
  OwnerJobsRoute: OwnerJobsRoute,
  OwnerProjectsRoute: OwnerProjectsRouteWithChildren,
  OwnerRecordsRoute: OwnerRecordsRoute,
  OwnerRolesRoute: OwnerRolesRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerTenantsRoute: OwnerTenantsRoute,
  OwnerUsersRoute: OwnerUsersRoute,
  OwnerVisitorsRoute: OwnerVisitorsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiTablesIdRouteChildren {
  ApiTablesIdColumnsRoute: typeof ApiTablesIdColumnsRoute
  ApiTablesIdRecordsRoute: typeof ApiTablesIdRecordsRoute
}

const ApiTablesIdRouteChildren: ApiTablesIdRouteChildren = {
  ApiTablesIdColumnsRoute: ApiTablesIdColumnsRoute,
  ApiTablesIdRecordsRoute: ApiTablesIdRecordsRoute,
}

const ApiTablesIdRouteWithChildren = ApiTablesIdRoute._addFileChildren(
  ApiTablesIdRouteChildren,
)

interface ApiPublicV1StorageRouteChildren {
  ApiPublicV1StorageFileRoute: typeof ApiPublicV1StorageFileRoute
}

const ApiPublicV1StorageRouteChildren: ApiPublicV1StorageRouteChildren = {
  ApiPublicV1StorageFileRoute: ApiPublicV1StorageFileRoute,
}

const ApiPublicV1StorageRouteWithChildren =
  ApiPublicV1StorageRoute._addFileChildren(ApiPublicV1StorageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  QuickstartRoute: QuickstartRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiAdminApiLogsRoute: ApiAdminApiLogsRoute,
  ApiAdminAuditLogsRoute: ApiAdminAuditLogsRoute,
  ApiAdminDbStatusRoute: ApiAdminDbStatusRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAdminVisitorsRoute: ApiAdminVisitorsRoute,
  ApiApiKeysIdRoute: ApiApiKeysIdRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiBillingPlansRoute: ApiBillingPlansRoute,
  ApiBillingUsageRoute: ApiBillingUsageRoute,
  ApiHnRolesRoute: ApiHnRolesRoute,
  ApiJobsDrainRoute: ApiJobsDrainRoute,
  ApiJobsEnqueueRoute: ApiJobsEnqueueRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiRecordsIdRoute: ApiRecordsIdRoute,
  ApiSsoLoginRoute: ApiSsoLoginRoute,
  ApiSsoSignupRoute: ApiSsoSignupRoute,
  ApiTablesIdRoute: ApiTablesIdRouteWithChildren,
  ApiApiKeysIndexRoute: ApiApiKeysIndexRoute,
  ApiBackupsIndexRoute: ApiBackupsIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiTablesIndexRoute: ApiTablesIndexRoute,
  ApiTeamIndexRoute: ApiTeamIndexRoute,
  ApiHnAuthLoginRoute: ApiHnAuthLoginRoute,
  ApiHnAuthLogoutRoute: ApiHnAuthLogoutRoute,
  ApiHnAuthMeRoute: ApiHnAuthMeRoute,
  ApiHnAuthSignupRoute: ApiHnAuthSignupRoute,
  ApiHnSitesDiscoverRoute: ApiHnSitesDiscoverRoute,
  ApiHnStorageIdRoute: ApiHnStorageIdRoute,
  ApiProjectsIdAnalyzeRoute: ApiProjectsIdAnalyzeRoute,
  ApiProjectsIdImportRoute: ApiProjectsIdImportRoute,
  ApiProjectsIdVerifyRoute: ApiProjectsIdVerifyRoute,
  ApiPublicSsoMeRoute: ApiPublicSsoMeRoute,
  ApiPublicSsoVerifyRoute: ApiPublicSsoVerifyRoute,
  ApiPublicV1StorageRoute: ApiPublicV1StorageRouteWithChildren,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiHnSitesIndexRoute: ApiHnSitesIndexRoute,
  ApiHnStorageIndexRoute: ApiHnStorageIndexRoute,
  ApiProjectsIdIndexRoute: ApiProjectsIdIndexRoute,
  ApiHnDbCollectionIdRoute: ApiHnDbCollectionIdRoute,
  ApiPublicV1DataCollectionRoute: ApiPublicV1DataCollectionRoute,
  ApiHnDbCollectionIndexRoute: ApiHnDbCollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
